[0m19:24:04.742964 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002355FACD4C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002356279D9A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002356279D730>]}


============================== 19:24:04.752938 | d4de21f9-4b77-4747-9808-13d587b3f8bd ==============================
[0m19:24:04.752938 [info ] [MainThread]: Running with dbt=1.7.0
[0m19:24:04.754901 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\melin\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:24:10.408259 [debug] [MainThread]: Starter project path: C:\Users\melin\anaconda3\envs\dataengineercamp\lib\site-packages\dbt\include\starter_project
[0m19:24:10.481680 [info ] [MainThread]: 
Your new dbt project "warehouse" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m19:24:10.484871 [info ] [MainThread]: Setting up your profile.
[0m19:24:17.146040 [error] [MainThread]: Encountered an error:

[0m19:24:17.176587 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\melin\anaconda3\envs\dataengineercamp\lib\site-packages\dbt\cli\requires.py", line 90, in wrapper
    result, success = func(*args, **kwargs)
  File "C:\Users\melin\anaconda3\envs\dataengineercamp\lib\site-packages\dbt\cli\requires.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\melin\anaconda3\envs\dataengineercamp\lib\site-packages\dbt\cli\main.py", line 515, in init
    results = task.run()
  File "C:\Users\melin\anaconda3\envs\dataengineercamp\lib\site-packages\dbt\task\init.py", line 344, in run
    self.setup_profile(profile_name)
  File "C:\Users\melin\anaconda3\envs\dataengineercamp\lib\site-packages\dbt\task\init.py", line 263, in setup_profile
    adapter = self.ask_for_adapter_choice()
  File "C:\Users\melin\anaconda3\envs\dataengineercamp\lib\site-packages\dbt\task\init.py", line 244, in ask_for_adapter_choice
    numeric_choice = click.prompt(prompt_msg, type=click.INT)
  File "C:\Users\melin\anaconda3\envs\dataengineercamp\lib\site-packages\click\termui.py", line 164, in prompt
    value = prompt_func(prompt)
  File "C:\Users\melin\anaconda3\envs\dataengineercamp\lib\site-packages\click\termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m19:24:17.208393 [debug] [MainThread]: Command `dbt init` failed at 19:24:17.206902 after 12.48 seconds
[0m19:24:17.212902 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002355FACD4C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000235627B34C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000235627B38B0>]}
[0m19:24:17.220903 [debug] [MainThread]: Flushing usage events
